Feature/i57/create basic routing
slakerZ/gamitude-ranks pull request #2
Opened 2019-12-29 11:43 UTC by Rustyiller

2019-12-29 20:02 UTC, kulaszewicz commented on package.json
> +    "sqlite3": "^4.0.9"
sqlite and sinon are not needed

2019-12-29 20:04 UTC, kulaszewicz commented on app.js
>  app.use('/users', usersRouter);
all user related stuff need to be deleted

2019-12-29 20:05 UTC, kulaszewicz requested changes
Added some comments about what to change

2020-01-05 19:04 UTC, kulaszewicz approved these changes
Looks good

2020-01-06 19:58 UTC, sj-lt approved these changes

2020-01-06 20:07 UTC, merged